plugins:
  - serverless-offline
  - serverless-dotenv-plugin

service: sqs-redis
frameworkVersion: '2||3'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  vpc:
    securityGroupIds:
      - sg-06b3510c74b619849
    subnetIds:
      - subnet-0e78d64e2d6144526
      - subnet-087f03708ffde1fe7
  iam:
    role:
      managedPolicies:
        - 'arn:aws:iam::992648939501:policy/SQSOperator'
        - 'arn:aws:iam::992648939501:policy/SendEmails'
        - 'arn:aws:iam::992648939501:policy/LambdaProxy'
functions:
  sqs-redis:
    handler: functions/sqsToRedis.receive
    events:
        - sqs:
            arn: arn:aws:sqs:eu-west-1:992648939501:landing-events
            batchSize: 10
            maximumBatchingWindow: 300
  read-redis:
    handler: functions/readRedis.read
    timeout: 10
  del-redis:
    handler: functions/delRedis.del
    timeout: 10
  report:
    handler: functions/sendReports.report
    vpc: ~
    timeout: 20
    events:
      - schedule:
          rate: rate(30 minutes)
      - httpApi:
          path: /report
          method: '*'
